-- a
SELECT p.* FROM T_POLICY p
JOIN T_CLIENT c ON p.CLIENT_NUMBER = c.CLIENT_NUMBER
WHERE p.POLICY_SUBMIT_DATE > DATE '2018-01-15' 
  AND EXTRACT(MONTH FROM c.BIRTH_DATE) = 9;

--b
SELECT p.*
FROM T_POLICY p
JOIN T_AGENT a ON p.AGENT_CODE = a.AGENT_CODE
WHERE p.POLICY_STATUS = 'INFORCE' 
  AND a.AGENT_OFFICE = 'JAKARTA';

-- c
MERGE INTO T_AGENT a
USING (
    SELECT AGENT_CODE, MAX((COMMISSION / PREMIUM) * 100) AS CALC_COMM
    FROM T_POLICY
    GROUP BY AGENT_CODE
) p
ON (a.AGENT_CODE = p.AGENT_CODE)
WHEN MATCHED THEN
    UPDATE SET a.BASIC_COMMISSION = p.CALC_COMM;

SELECT * FROM T_AGENT;

-- d 
UPDATE T_POLICY
SET POLICY_DUE_DATE = LAST_DAY(POLICY_SUBMIT_DATE + 30);

SELECT * FROM T_POLICY;

-- e
SELECT 
    p.AGENT_CODE, 
    a.AGENT_NAME, 
    p.POLICY_NUMBER, 
    p.PREMIUM, 
    1000000 AS NOMINAL_DISCOUNT,
    (p.PREMIUM - 1000000) AS NET_PREMIUM
FROM T_POLICY p
JOIN T_AGENT a ON p.AGENT_CODE = a.AGENT_CODE
ORDER BY NET_PREMIUM ASC;